language: perl
sudo: false

install:
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps --missing | cpanm -n
  - cpanm -n https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/Clustericious-1.10_03.tar.gz

script:
  - dzil test -v

perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
